### ISSUE TITLE
Imposter website found, shows up first in google results

### ISSUE THREAD

**Issue by Andrew-J-Larson** [lubuntu-team/lubuntu.me#2]
https://lubuntu.net/

Might want to check it out and take it down.

**Comment by wxl** [comment]
This is has been discussed many times, including on the [open bug](https://bugs.launchpad.net/lubuntu-website/+bug/1608306) from the canonical place that the Lubuntu Team does take reports from. It's still in progress because it is.

I would suggest not reporting bugs with the Lubuntu project on GitHub, but instead follow the directions shown on our [wiki page](https://phab.lubuntu.me/w/bugs/) on the subject.
